server:
  port: 8989
  servlet:
    context-path: /yingx
    jsp:
      init-parameters:
        development: true
spring:
  mvc:
    view:
      suffix: .jsp
      prefix: /
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yingx?characterEncoding=utf-8
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 50MB  #单个文件最大为100MB
      max-request-size: 100MB  #一次请求最多携带100MB
mybatis:
  type-aliases-package: com.baizhi.zsj.entity
  mapper-locations: classpath:com/baizhi/zsj/mapper/*Mapper.xml
